-- Seed file generated by script

INSERT INTO usuarios (id, email, nombre, apellidos, rol, foto_url) VALUES ('57b8f74c-7eeb-4978-a03d-11df784f97e5', 'héctor@mineros.com', 'Héctor', 'García', 'jugador', 'https://i.pravatar.cc/150?u=hector');
INSERT INTO plantilla (jugador_id, equipo, dorsal, demarcacion, posicion, categoria, rol_funcional_primario, rol_funcional_secundario, pierna_habil, altura_cm, peso_kg) VALUES ('57b8f74c-7eeb-4978-a03d-11df784f97e5', 'Mineros Zacatecas', 4, 'DEFENSA', 'Central', '2003', 'Inicio', 'Base', 'Diestro', 188, 82);

INSERT INTO usuarios (id, email, nombre, apellidos, rol, foto_url) VALUES ('b5362a31-034b-42aa-8b19-daf0d0f9f80a', 'andrés@mineros.com', 'Andrés', 'Ramírez', 'jugador', 'https://i.pravatar.cc/150?u=andres');
INSERT INTO plantilla (jugador_id, equipo, dorsal, demarcacion, posicion, categoria, rol_funcional_primario, rol_funcional_secundario, pierna_habil, altura_cm, peso_kg) VALUES ('b5362a31-034b-42aa-8b19-daf0d0f9f80a', 'Mineros Zacatecas', 8, 'CENTROCAMPISTA', 'Interior', '2005', 'Cuadrados', 'Profundidad', 'Zurdo', 175, 68);

INSERT INTO usuarios (id, email, nombre, apellidos, rol, foto_url) VALUES ('1fde5495-efd3-4d98-91bc-7e41da4c1b02', 'carlos@mineros.com', 'Carlos', 'López', 'jugador', 'https://i.pravatar.cc/150?u=carlos');
INSERT INTO plantilla (jugador_id, equipo, dorsal, demarcacion, posicion, categoria, rol_funcional_primario, rol_funcional_secundario, pierna_habil, altura_cm, peso_kg) VALUES ('1fde5495-efd3-4d98-91bc-7e41da4c1b02', 'Mineros Zacatecas', 11, 'DELANTERO', 'Extremo', '2004', 'Amplitud', 'Profundidad', 'Diestro', 170, 65);

