const fs = require('fs');
const crypto = require('crypto');

const mockPlayers = [
  {
    id: crypto.randomUUID(),
    nombre: "Héctor",
    apellidos: "García",
    fotografia: "https://i.pravatar.cc/150?u=hector",
    plantilla: {
      demarcacion: "DEFENSA", posicion: "Central", categoria: "2003",
      rol_funcional_primario: "Inicio", rol_funcional_secundario: "Base",
      pierna_habil: "Diestro", altura_cm: 188, peso_kg: 82, dorsal: 4, equipo: "Mineros Zacatecas"
    }
  },
  {
    id: crypto.randomUUID(),
    nombre: "Andrés",
    apellidos: "Ramírez",
    fotografia: "https://i.pravatar.cc/150?u=andres",
    plantilla: {
      demarcacion: "CENTROCAMPISTA", posicion: "Interior", categoria: "2005",
      rol_funcional_primario: "Cuadrados", rol_funcional_secundario: "Profundidad",
      pierna_habil: "Zurdo", altura_cm: 175, peso_kg: 68, dorsal: 8, equipo: "Mineros Zacatecas"
    }
  },
  {
    id: crypto.randomUUID(),
    nombre: "Carlos",
    apellidos: "López",
    fotografia: "https://i.pravatar.cc/150?u=carlos",
    plantilla: {
      demarcacion: "DELANTERO", posicion: "Extremo", categoria: "2004",
      rol_funcional_primario: "Amplitud", rol_funcional_secundario: "Profundidad",
      pierna_habil: "Diestro", altura_cm: 170, peso_kg: 65, dorsal: 11, equipo: "Mineros Zacatecas"
    }
  }
];

let sql = `-- Seed file generated by script\n\n`;

for (const p of mockPlayers) {
  sql += `INSERT INTO usuarios (id, email, nombre, apellidos, rol, foto_url) VALUES ('${p.id}', '${p.nombre.toLowerCase()}@mineros.com', '${p.nombre}', '${p.apellidos}', 'jugador', '${p.fotografia}');\n`;
  sql += `INSERT INTO plantilla (jugador_id, equipo, dorsal, demarcacion, posicion, categoria, rol_funcional_primario, rol_funcional_secundario, pierna_habil, altura_cm, peso_kg) VALUES ('${p.id}', '${p.plantilla.equipo}', ${p.plantilla.dorsal}, '${p.plantilla.demarcacion}', '${p.plantilla.posicion}', '${p.plantilla.categoria}', '${p.plantilla.rol_funcional_primario}', '${p.plantilla.rol_funcional_secundario}', '${p.plantilla.pierna_habil}', ${p.plantilla.altura_cm}, ${p.plantilla.peso_kg});\n\n`;
}

fs.writeFileSync('supabase/seed.sql', sql);
console.log('Seed SQL generated at supabase/seed.sql');
